CC = gcc
CFLAGS = -ansi -pedantic -errors

grepFromFile: Yasin_Tulumen_121044020.o
	$(CC) -o grepFromDir Yasin_Tulumen_121044020.c

Yasin_Tulumen_121044020.o: Yasin_Tulumen_121044020.c
	$(CC) $(CFLAGS) -c Yasin_Tulumen_121044020.c

clean:
	rm -f grepFromDir *.o


	
